shiny:
  proxy:
    title: MilkyWay ShinyProxy
    logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 8080
    authentication: simple
    admin-groups: admin
    # Simple auth configuration
    users:
    - name: admin
      password: admin
      groups: admin
    - name: collaborators
      password: collaborators
      groups: collaborators
    # Docker configuration
    docker:
      cert-path: /home/none
      url: http://milkyway-shinyproxy:2375
      host: milkyway-shinyproxy
      port-range-start: 20000
  apps:
  - name: milkyway
    display-name: MilkyWay Proteomics
    description: An interface to the Galaxy MilkyWay Workflow System
    docker-cmd: ["R", "-e shiny::runApp('/root/milkyway',port=3838,host='0.0.0.0')"]
    docker-image: wbarshop/milkyway_shiny:latest
    groups: scientists, collaborators, admin

logging:
  file:
    shinyproxy.log

